#! /bin/sh
wmname LG3D &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
#bspc config border_radius       2
bspc config window_gap          12

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      false

######
bspc config click_to_focus true
bspc config single_monocle true
bspc config pointer_action3 move
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
######



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom --backend glx &
feh --no-fehbg --bg-fill /usr/share/wallpapers/sunset.png &
~/.config/polybar/./launch.sh --grayblocks &
#xss-lock -l /usr/share/doc/xss-lock/transfer-sleep-lock-generic-delay.sh &
bspc config focus_follows_pointer true
